version: '3.2'
services:


  # # ElasticSearch
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  #   environment:
  #     - cluster.name=combine-elasticsearch
  #     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  #     - xpack.security.enabled=false
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     combinenet:
  #       ipv4_address: 10.5.0.2


  # # MongoDB
  # mongo:
  #   build: ./mongo
  #   volumes:
  #     - mongodata:/data/db
  #   ports:
  #     - 27017:27017
  #   command: "--config /etc/mongod.conf"
  #   networks:
  #     combinenet:
  #       ipv4_address: 10.5.0.3


  # # MySQL
  # mysql:
  #   build: ./mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: combine
  #   volumes:
  #     - mysqldata:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   command: "--default-authentication-plugin=mysql_native_password"
  #   networks:
  #     combinenet:
  #       ipv4_address: 10.5.0.4


  # # Redis
  # redis:
  #   image: redis:4.0
  #   ports:
  #     - 6379:6379
  #   networks:
  #     combinenet:
  #       ipv4_address: 10.5.0.5


  hadoop-namenode:
    build:
      context: ./spark
      dockerfile: Dockerfile
      args:
        SPARK_VERSION: "${SPARK_VERSION}"
        HADOOP_VERSION: "${HADOOP_VERSION}"
    volumes:
      - hdfs:/hdfs
      - type: bind
        source: ./spark/config/hadoop/core-site.xml
        target: /opt/hadoop/etc/hadoop/core-site.xml
      - type: bind
        source: ./spark/config/hadoop/hdfs-site.xml
        target: /opt/hadoop/etc/hadoop/hdfs-site.xml
    ports:
      - 8020:8020
    # environment:
    #   - "SPARK_HOME=/usr/spark-2.3.2"
    command:  /opt/hadoop/bin/hdfs --config /opt/hadoop/etc/hadoop namenode
    networks:
      combinenet:
        ipv4_address: 10.5.0.6


  hadoop-datanode:
    build:
      context: ./spark
      dockerfile: Dockerfile
      args:
        SPARK_VERSION: "${SPARK_VERSION}"
        HADOOP_VERSION: "${HADOOP_VERSION}"
    volumes:
      - hdfs:/hdfs
      - type: bind
        source: ./spark/config/hadoop/core-site.xml
        target: /opt/hadoop/etc/hadoop/core-site.xml
      - type: bind
        source: ./spark/config/hadoop/hdfs-site.xml
        target: /opt/hadoop/etc/hadoop/hdfs-site.xml
    ports:
      - 50070:50070
      - 50075:50075
    # environment:
    #   - "SPARK_HOME=/usr/spark-2.3.2"
    command:  /opt/hadoop/bin/hdfs --config /opt/hadoop/etc/hadoop datanode
    networks:
      combinenet:
        ipv4_address: 10.5.0.7


# Volumes
volumes:
  esdata:
    driver: local
  mongodata:
    driver: local
  mysqldata:
    driver: local
  combinehome:
    driver: local
  hdfs:
    driver: local


# Networks
networks:
  combinenet:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
